### ISSUE TITLE
编译出来的libnative_lib.so放到其他工程上使用问题

### ISSUE THREAD

**Issue by xmutzlq** [TUGOhost/anti_Android#19]
为什么编译出来的libnative_lib.so放到其他工程上使用anti_MemDump反调试就会无效，而在此工程上就可以反调试的呢？

**Comment by TUGOhost** [comment]
额，你是用这个项目编译出来的libnative_lib.so放到别的项目中使用的吗。这个没测试过，你可以在你app工程新加module，然后复用原本的代码。这个我打算以后抽离出module出来

**Comment by xmutzlq** [comment]
有没有办法用引so的方式使用，而不是module的方式呢？
在这个项目中，我改成用jniLibs的方式使用libnative_lib.so也是无法触发反调试，只有直接跑工程才能触发反调试。
可以帮忙看下什么问题吗？

**Comment by TUGOhost** [comment]
现在master分支是module跟app分开的，如果想要单独编译so的话，可能需要改造cmake文件。
