### ISSUE TITLE
Add Android Emulator detection

### ISSUE THREAD

**Issue by polaryy** [TUGOhost/anti_Android#20]
You can add a simple android emulator detection against bluestacks by checking if one of the following files exist on the system.

"/data/.bluestacks.prop"  
"/data/.bstconf.prop"  
"/mnt/windows"
"/mnt/windows/BstSharedFolder"
"/mnt/prebundledapps/downloads/com.bluestacks.home.apk"
"/mnt/prebundledapps/bst_appdetails_bgptest"
"/system/priv-app/com.bluestacks.bstfolder.apk"

**Comment by TUGOhost** [comment]
Detect emulator, mostly by detecting relevant file characteristics, which are not too accurate.Later update.

**Comment by TUGOhost** [comment]
update
