### ISSUE TITLE
手里的真机被判断成了模拟器

### ISSUE THREAD

**Issue by est7** [TUGOhost/anti_Android#21]
```
std::string AntiEmulator::check() {
    std::string result = "security";
    std::vector<std::string> list_of_files =
            {
                    "/boot/bstmods/vboxguest.ko",
                    "/boot/bstmods/vboxsf.ko",
                    "/dev/qemu_pipe",
                    "/dev/socket/qemud",
                    "/dev/socket/windroyed-audio",
                    "/dev/socket/windroyed-camera",
                    "/dev/socket/windroyed-gps",
                    "/dev/socket/windroyed-sensors",
                    "/dev/vboxguest"
            };
    for (auto file: list_of_files) {
        if (check_of_file(file) || dir(file)) {
            result = "checked";
        }
    }

    std::vector<std::string> list_of_props = {
            "ro.redfinger.server.enable",
            "androVM.vbox_dpi",
            "androVM.vbox_graph_mode"
    };

    for (auto prop: list_of_props) {
        if (check_of_prop(prop).find("redfinger") != std::string::npos) {
            result = "checked";
        }
    }

    LOGE("result: %s", result.c_str());
    return result;
}

```
看了下判断check_of_file(file) || dir(file) 上面9个路径都走进走个语句内了...
![image](https://user-images.githubusercontent.com/17064360/211710699-70adac08-ca12-4313-a204-9c30f9665769.png)

**Comment by est7** [comment]
fd=-1 应该返false吧

**Comment by est7** [comment]
![image](https://user-images.githubusercontent.com/17064360/211712050-bb68d0d2-86a9-4527-a6a5-1b7c91b0eeba.png)
这为什么fd 不等于 errno

**Comment by est7** [comment]
应该这么写吧?https://www.cnblogs.com/kovogo/p/15535780.html

**Comment by est7** [comment]
顺便补充一些
02-13 12:29:37.572 15179-16035/? D/XX_N: stat源路径 /boot/bstmods/vboxguest.ko

02-13 12:29:37.574 15179-16035/? D/XX_N: stat源路径 /boot/bstmods/vboxsf.ko

02-13 12:29:37.575 15179-16035/? D/XX_N: stat源路径 /dev/qemu_pipe

02-13 12:29:37.576 15179-16035/? D/XX_N: stat源路径 /dev/socket/qemud

02-13 12:29:37.577 15179-16035/? D/XX_N: stat源路径 /dev/socket/windroyed-audio

02-13 12:29:37.578 15179-16035/? D/XX_N: stat源路径 /dev/socket/windroyed-camera

02-13 12:29:37.579 15179-16035/? D/XX_N: stat源路径 /dev/socket/windroyed-gps

02-13 12:29:37.581 15179-16035/? D/XX_N: stat源路径 /dev/socket/windroyed-sensors

02-13 12:29:37.582 15179-16035/? D/XX_N: stat源路径 /dev/vboxguest

02-13 12:29:37.583 15179-16035/? D/XX_N: stat源路径 /dev/vboxpci

02-13 12:29:37.586 15179-16035/? D/XX_N: stat源路径 /dev/vboxuser

02-13 12:29:37.588 15179-16035/? D/XX_N: stat源路径 /dev/vga_arbiter

02-13 12:29:37.590 15179-16035/? D/XX_N: stat源路径 /fstab.nox

02-13 12:29:37.591 15179-16035/? D/XX_N: stat源路径 /fstab.vbox86

02-13 12:29:37.593 15179-16035/? D/XX_N: stat源路径 /init.nox.rc

02-13 12:29:37.596 15179-16035/? D/XX_N: stat源路径 /init.vbox86.rc

02-13 12:29:37.597 15179-16035/? D/XX_N: stat源路径 /init.vbox86p.rc

02-13 12:29:37.598 15179-16035/? D/XX_N: stat源路径 /init.windroye.rc

02-13 12:29:37.600 15179-16035/? D/XX_N: stat源路径 /init.windroye.sh

02-13 12:29:37.601 15179-16035/? D/XX_N: stat源路径 /init.x86.rc

02-13 12:29:37.604 15179-16035/? D/XX_N: stat源路径 /proc/irq/20/vboxguest

02-13 12:29:37.606 15179-16035/? D/XX_N: stat源路径 /sys/bus/pci/drivers/vboxguest

02-13 12:29:37.607 15179-16035/? D/XX_N: stat源路径 /sys/bus/pci/drivers/vboxpci

02-13 12:29:37.608 15179-16035/? D/XX_N: stat源路径 /sys/bus/platform/devices/qemu_pipe

02-13 12:29:37.609 15179-16035/? D/XX_N: stat源路径 /sys/bus/platform/drivers/qemu_pipe

02-13 12:29:37.610 15179-16035/? D/XX_N: stat源路径 /sys/bus/platform/drivers/qemu_pipe/qemu_pipe

02-13 12:29:37.611 15179-16035/? D/XX_N: stat源路径 /sys/bus/platform/drivers/qemu_trace

02-13 12:29:37.612 15179-16035/? D/XX_N: stat源路径 /sys/bus/virtio/drivers/itolsvmlgtp

02-13 12:29:37.614 15179-16035/? D/XX_N: stat源路径 /sys/bus/virtio/drivers/itoolsvmhft

02-13 12:29:37.616 15179-16035/? D/XX_N: stat源路径 /sys/class/bdi/vboxsf-1

02-13 12:29:37.618 15179-16035/? D/XX_N: stat源路径 /sys/class/bdi/vboxsf-2

02-13 12:29:37.620 15179-16035/? D/XX_N: stat源路径 /sys/class/bdi/vboxsf-3

02-13 12:29:37.621 15179-16035/? D/XX_N: stat源路径 /sys/class/misc/qemu_pipe

02-13 12:29:37.623 15179-16035/? D/XX_N: stat源路径 /sys/class/misc/vboxguest

02-13 12:29:37.624 15179-16035/? D/XX_N: stat源路径 /sys/class/misc/vboxuser

02-13 12:29:37.626 15179-16035/? D/XX_N: stat源路径 /sys/devices/platform/qemu_pipe

02-13 12:29:37.629 15179-16035/? D/XX_N: stat源路径 /sys/devices/virtual/bdi/vboxsf-1

02-13 12:29:37.632 15179-16035/? D/XX_N: stat源路径 /sys/devices/virtual/bdi/vboxsf-2

02-13 12:29:37.634 15179-16035/? D/XX_N: stat源路径 /sys/devices/virtual/bdi/vboxsf-3

02-13 12:29:37.636 15179-16035/? D/XX_N: stat源路径 /sys/devices/virtual/misc/qemu_pipe

02-13 12:29:37.638 15179-16035/? D/XX_N: stat源路径 /sys/devices/virtual/misc/vboxguest

02-13 12:29:37.639 15179-16035/? D/XX_N: stat源路径 /sys/devices/virtual/misc/vboxpci

02-13 12:29:37.640 15179-16035/? D/XX_N: stat源路径 /sys/devices/virtual/misc/vboxuser

02-13 12:29:37.643 15179-16035/? D/XX_N: stat源路径 /sys/fs/selinux/booleans/in_qemu

02-13 12:29:37.644 15179-16035/? D/XX_N: stat源路径 /sys/kernel/debug/bdi/vboxsf-1

02-13 12:29:37.645 15179-16035/? D/XX_N: stat源路径 /sys/kernel/debug/bdi/vboxsf-2

02-13 12:29:37.646 15179-16035/? D/XX_N: stat源路径 /sys/kernel/debug/x86

02-13 12:29:37.647 15179-16035/? D/XX_N: stat源路径 /sys/module/qemu_trace_sysfs

02-13 12:29:37.648 15179-16035/? D/XX_N: stat源路径 /sys/module/vboxguest/drivers/pci:vboxguest

02-13 12:29:37.649 15179-16035/? D/XX_N: stat源路径 /sys/module/vboxsf

02-13 12:29:37.650 15179-16035/? D/XX_N: stat源路径 /sys/module/vboxvideo

02-13 12:29:37.651 15179-16035/? D/XX_N: stat源路径 /sys/module/virtio_pt_ie/drivers/virtio:itoolsvmlgtp

02-13 12:29:37.652 15179-16035/? D/XX_N: stat源路径 /sys/module/virtio_pt/drivers/virtio:itoolsvmhft

02-13 12:29:37.653 15179-16035/? D/XX_N: stat源路径 /sys/qemu_trace

02-13 12:29:37.654 15179-16035/? D/XX_N: stat源路径 /system/bin/androVM-vbox-sf

02-13 12:29:37.654 15179-16035/? D/XX_N: stat源路径 /system/bin/droid4x

02-13 12:29:37.655 15179-16035/? D/XX_N: stat源路径 /system/bin/droid4x_setprop

02-13 12:29:37.657 15179-16035/? D/XX_N: stat源路径 /system/bin/droid4x-prop

02-13 12:29:37.658 15179-16035/? D/XX_N: stat源路径 /system/bin/droid4x-vbox-sf

02-13 12:29:37.659 15179-16035/? D/XX_N: stat源路径 /system/bin/enable_nox

02-13 12:29:37.660 15179-16035/? D/XX_N: stat源路径 /system/bin/genymotion-vbox-sf

02-13 12:29:37.660 15179-16035/? D/XX_N: stat源路径 /system/bin/microvirt_setprop

02-13 12:29:37.662 15179-16035/? D/XX_N: stat源路径 /system/bin/microvirt-prop

02-13 12:29:37.663 15179-16035/? D/XX_N: stat源路径 /system/bin/microvirt-vbox-sf

02-13 12:29:37.663 15179-16035/? D/XX_N: stat源路径 /system/bin/microvirtd

02-13 12:29:37.664 15179-16035/? D/XX_N: stat源路径 /system/bin/mount.vboxsf

02-13 12:29:37.665 15179-16035/? D/XX_N: stat源路径 /system/bin/nox

02-13 12:29:37.666 15179-16035/? D/XX_N: stat源路径 /system/bin/nox_setprop

02-13 12:29:37.667 15179-16035/? D/XX_N: stat源路径 /system/bin/nox-prop

02-13 12:29:37.668 15179-16035/? D/XX_N: stat源路径 /system/bin/nox-vbox-sf

02-13 12:29:37.669 15179-16035/? D/XX_N: stat源路径 /system/bin/noxd

02-13 12:29:37.670 15179-16035/? D/XX_N: stat源路径 /system/bin/noxscreen

02-13 12:29:37.671 15179-16035/? D/XX_N: stat源路径 /system/bin/noxspeedup

02-13 12:29:37.672 15179-16035/? D/XX_N: stat源路径 /system/bin/OpenglService

02-13 12:29:37.673 15179-16035/? D/XX_N: stat源路径 /system/bin/qemu-props

02-13 12:29:37.674 15179-16035/? D/XX_N: stat源路径 /system/bin/qemud

02-13 12:29:37.675 15179-16035/? D/XX_N: stat源路径 /system/bin/shellnox

02-13 12:29:37.676 15179-16035/? D/XX_N: stat源路径 /system/bin/windroyed

02-13 12:29:37.677 15179-16035/? D/XX_N: stat源路径 /system/etc/init.droid4x.sh

02-13 12:29:37.678 15179-16035/? D/XX_N: stat源路径 /system/etc/init.tiantian.sh

02-13 12:29:37.679 15179-16035/? D/XX_N: stat源路径 /system/lib/egl/libEGL_tiantianVM.so

02-13 12:29:37.680 15179-16035/? D/XX_N: stat源路径 /system/lib/egl/libEGL_windroye.so

02-13 12:29:37.681 15179-16035/? D/XX_N: stat源路径 /system/lib/egl/libGLESv1_CM_tiantianVM.so

02-13 12:29:37.682 15179-16035/? D/XX_N: stat源路径 /system/lib/egl/libGLESv1_CM_windroye.so

02-13 12:29:37.683 15179-16035/? D/XX_N: stat源路径 /system/lib/egl/libGLESv2_tiantianVM.so

02-13 12:29:37.684 15179-16035/? D/XX_N: stat源路径 /system/lib/egl/libGLESv2_windroye.so

02-13 12:29:37.684 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/audio.primary.vbox86.so

02-13 12:29:37.685 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/audio.primary.windroye.so

02-13 12:29:37.686 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/audio.primary.x86.so

02-13 12:29:37.687 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/autio.primary.nox.so

02-13 12:29:37.688 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/camera.vbox86.so

02-13 12:29:37.689 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/camera.windroye.jpeg.so

02-13 12:29:37.690 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/camera.windroye.so

02-13 12:29:37.691 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/camera.x86.so

02-13 12:29:37.692 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/gps.nox.so

02-13 12:29:37.693 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/gps.vbox86.so

02-13 12:29:37.694 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/gps.windroye.so

02-13 12:29:37.695 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/gralloc.nox.so

02-13 12:29:37.696 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/gralloc.vbox86.so

02-13 12:29:37.697 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/gralloc.windroye.so

02-13 12:29:37.698 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/sensors.nox.so

02-13 12:29:37.699 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/sensors.vbox86.so

02-13 12:29:37.700 15179-16035/? D/XX_N: stat源路径 /system/lib/hw/sensors.windroye.so

02-13 12:29:37.701 15179-16035/? D/XX_N: stat源路径 /system/lib/init.nox.sh

02-13 12:29:37.702 15179-16035/? D/XX_N: stat源路径 /system/lib/libc_malloc_debug_qemu.so

02-13 12:29:37.703 15179-16035/? D/XX_N: stat源路径 /system/lib/libclcore_x86.bc

02-13 12:29:37.704 15179-16035/? D/XX_N: stat源路径 /system/lib/libdroid4x.so

02-13 12:29:37.704 15179-16035/? D/XX_N: stat源路径 /system/lib/libGM_OpenglSystemCommon.so

02-13 12:29:37.706 15179-16035/? D/XX_N: stat源路径 /system/lib/libnoxd.so

02-13 12:29:37.706 15179-16035/? D/XX_N: stat源路径 /system/lib/libnoxspeedup.so

02-13 12:29:37.707 15179-16035/? D/XX_N: stat源路径 /system/lib/modules/3.10.30-android-x86.hd+

02-13 12:29:37.708 15179-16035/? D/XX_N: stat源路径 /system/lib/vboxguest.ko

02-13 12:29:37.709 15179-16035/? D/XX_N: stat源路径 /system/lib/vboxpcism.ko

02-13 12:29:37.710 15179-16035/? D/XX_N: stat源路径 /system/lib/vboxsf.ko

02-13 12:29:37.711 15179-16035/? D/XX_N: stat源路径 /system/lib/vboxvideo.ko

02-13 12:29:37.712 15179-16035/? D/XX_N: stat源路径 /system/lib64/libc_malloc_debug_qemu.so

02-13 12:29:37.713 15179-16035/? D/XX_N: stat源路径 /system/usr/idc/droid4x_Virtual_Input.idc

02-13 12:29:37.714 15179-16035/? D/XX_N: stat源路径 /system/usr/idc/Genymotion_Virtual_Input.idc

02-13 12:29:37.715 15179-16035/? D/XX_N: stat源路径 /system/usr/idc/nox_Virtual_Input.idc

02-13 12:29:37.716 15179-16035/? D/XX_N: stat源路径 /system/usr/idc/windroye.idc

02-13 12:29:37.717 15179-16035/? D/XX_N: stat源路径 /system/usr/keychars/nox_gpio.kcm

02-13 12:29:37.718 15179-16035/? D/XX_N: stat源路径 /system/usr/keychars/windroye.kcm

02-13 12:29:37.719 15179-16035/? D/XX_N: stat源路径 /system/usr/Keylayout/droid4x_Virtual_Input.kl

02-13 12:29:37.720 15179-16035/? D/XX_N: stat源路径 /system/usr/keylayout/Genymotion_Virtual_Input.kl

02-13 12:29:37.721 15179-16035/? D/XX_N: stat源路径 /system/usr/keylayout/nox_gpio.kl

02-13 12:29:37.722 15179-16035/? D/XX_N: stat源路径 /system/usr/keylayout/nox_Virtual_Input.kl

02-13 12:29:37.723 15179-16035/? D/XX_N: stat源路径 /system/usr/keylayout/windroye.kl

02-13 12:29:37.724 15179-16035/? D/XX_N: stat源路径 /system/xbin/noxsu

02-13 12:29:37.725 15179-16035/? D/XX_N: stat源路径 /ueventd.android_x86.rc

02-13 12:29:37.726 15179-16035/? D/XX_N: stat源路径 /ueventd.goldfish.rc

02-13 12:29:37.727 15179-16035/? D/XX_N: stat源路径 /sys/module/vboxsf

02-13 12:29:37.728 15179-16035/? D/XX_N: stat源路径 /sys/module/vboxguest

02-13 12:29:37.729 15179-16035/? D/XX_N: stat源路径 /sys/module/vboxpcism

02-13 12:29:37.730 15179-16035/? D/XX_N: stat源路径 /system/droid4x

02-13 12:29:37.731 15179-16035/? D/XX_N: stat源路径 /system/app/GenymotionLayout

02-13 12:29:37.732 15179-16035/? D/XX_N: stat源路径 /dev/usb_accessory

02-13 12:29:37.733 15179-16035/? D/XX_N: stat源路径 /dev/mtp_usb

02-13 12:29:37.734 15179-16035/? D/XX_N: stat源路径 /sdcard/Android/data/com.redfinger.gamemanage



02-13 12:29:37.735 15179-16035/? D/XX_N: __system_property_get ro.redfinger.server.enable = 

02-13 12:29:37.735 15179-16035/? D/XX_N: __system_property_get androVM.vbox_dpi = 

02-13 12:29:37.736 15179-16035/? D/XX_N: __system_property_get androVM.vbox_graph_mode = 

02-13 12:29:37.736 15179-16035/? D/XX_N: __system_property_get init.svc.memud = 

02-13 12:29:37.736 15179-16035/? D/XX_N: __system_property_get init.svc.qemu-props = 

02-13 12:29:37.736 15179-16035/? D/XX_N: __system_property_get /ueventd.vbox86.rc = 

02-13 12:29:37.737 15179-16035/? D/XX_N: __system_property_get init.svc.vbox86-setup = 

02-13 12:29:37.737 15179-16035/? D/XX_N: __system_property_get init.svc.windroye-setup = 

02-13 12:29:37.737 15179-16035/? D/XX_N: __system_property_get init.svc.windroyed = 

02-13 12:29:37.737 15179-16035/? D/XX_N: __system_property_get microvirt.vbox_dpi = 

02-13 12:29:37.737 15179-16035/? D/XX_N: __system_property_get microvirt.vbox_sdcard_drive = 

02-13 12:29:37.737 15179-16035/? D/XX_N: __system_property_get persisit.windroye.device.id = 

02-13 12:29:37.738 15179-16035/? D/XX_N: __system_property_get persist.itools.board = 

02-13 12:29:37.738 15179-16035/? D/XX_N: __system_property_get persist.itools.deflauncher = 

02-13 12:29:37.738 15179-16035/? D/XX_N: __system_property_get persist.itools.device = 

02-13 12:29:37.738 15179-16035/? D/XX_N: __system_property_get persist.itools.manufacturer = 

02-13 12:29:37.738 15179-16035/? D/XX_N: __system_property_get persist.itools.model = 

02-13 12:29:37.739 15179-16035/? D/XX_N: __system_property_get persist.itools.modem.defimei = 

02-13 12:29:37.739 15179-16035/? D/XX_N: __system_property_get persist.itools.modem.defimsi = 

02-13 12:29:37.739 15179-16035/? D/XX_N: __system_property_get persist.itools.name = 

02-13 12:29:37.739 15179-16035/? D/XX_N: __system_property_get qemu.hw.mainkeys = 

02-13 12:29:37.740 15179-16035/? D/XX_N: __system_property_get qemu.sf.fake_camera = 

02-13 12:29:37.740 15179-16035/? D/XX_N: __system_property_get qemu.sf.lcd_density = 

02-13 12:29:37.740 15179-16035/? D/XX_N: __system_property_get ro.kernel.android.qemud = 

02-13 12:29:37.740 15179-16035/? D/XX_N: __system_property_get ro.kernel.qemu = 

02-13 12:29:37.740 15179-16035/? D/XX_N: __system_property_get ro.kernel.qemu.gles = 

02-13 12:29:37.740 15179-16035/? D/XX_N: __system_property_get ro.kernel.windroye.gles = 

02-13 12:29:37.740 15179-16035/? D/XX_N: __system_property_get windroyed.gps.accuracy = 

02-13 12:29:37.740 15179-16035/? D/XX_N: __system_property_get windroyed.gps.altitude = 

02-13 12:29:37.741 15179-16035/? D/XX_N: __system_property_get windroyed.gps.bearing = 

02-13 12:29:37.741 15179-16035/? D/XX_N: __system_property_get ro.boot.hardware = qcom (替换后)

02-13 12:29:37.741 15179-16035/? D/XX_N: __system_property_get ro.hardware = qcom (替换后)

02-13 12:29:37.741 15179-16035/? D/XX_N: __system_property_get ro.boot.hardware = qcom (替换后)

02-13 12:29:37.741 15179-16035/? D/XX_N: __system_property_get ro.hardware = qcom (替换后)







2020-06-09 02:00:03.596 6982-7033/? D/XX_N: stat源路径 /system/bin/qemu_props

2020-06-09 02:00:03.596 6982-7033/? D/XX_N: stat源路径 /system/bin/androVM-prop

2020-06-09 02:00:03.597 6982-7033/? D/XX_N: stat源路径 /system/bin/microvirt-prop

2020-06-09 02:00:03.597 6982-7033/? D/XX_N: stat源路径 /system/lib/libdroid4x.so

2020-06-09 02:00:03.597 6982-7033/? D/XX_N: stat源路径 /system/bin/windroyed

2020-06-09 02:00:03.598 6982-7033/? D/XX_N: stat源路径 /system/bin/microvirtd

2020-06-09 02:00:03.598 6982-7033/? D/XX_N: stat源路径 /system/bin/nox-prop

2020-06-09 02:00:03.598 6982-7033/? D/XX_N: stat源路径 /system/bin/ttVM-prop

2020-06-09 02:00:03.598 6982-7033/? D/XX_N: stat源路径 /system/bin/droid4x-prop

2020-06-09 02:00:03.598 6982-7033/? D/XX_N: stat源路径 /data/.bluestacks.prop

2020-06-09 02:00:03.598 6982-7033/? D/XX_N: __system_property_get init.svc.vbox86-setup = 

2020-06-09 02:00:03.598 6982-7033/? D/XX_N: __system_property_get init.svc.droid4x = 

2020-06-09 02:00:03.599 6982-7033/? D/XX_N: __system_property_get init.svc.qemud = 

2020-06-09 02:00:03.599 6982-7033/? D/XX_N: __system_property_get init.svc.su_kpbs_daemon = 

2020-06-09 02:00:03.599 6982-7033/? D/XX_N: __system_property_get init.svc.noxd = 

2020-06-09 02:00:03.599 6982-7033/? D/XX_N: __system_property_get init.svc.ttVM_x86-setup = 

2020-06-09 02:00:03.601 6982-7033/? D/XX_N: __system_property_get init.svc.xxkmsg = 

2020-06-09 02:00:03.601 6982-7033/? D/XX_N: __system_property_get init.svc.microvirtd = 

2020-06-09 02:00:03.601 6982-7033/? D/XX_N: __system_property_get ro.kernel.android.qemud = 

2020-06-09 02:00:03.601 6982-7033/? D/XX_N: __system_property_get androVM.vbox_dpi = 

2020-06-09 02:00:03.601 6982-7033/? D/XX_N: __system_property_get androVM.vbox_graph_mode =

**Comment by TUGOhost** [comment]
fd == errno 返回false，https://github.com/TUGOhost/anti_Android/blob/main/anti/src/main/cpp/check/anti_emulator.cpp#L52，https://github.com/TUGOhost/anti_Android/blob/main/anti/src/main/cpp/check/anti_emulator.cpp#L60。可能是list中某个文件路径判断错误。底下的那么一堆，我当时懒得加，随便写了点。
